name: Android CI

on:
    pull_request:
        branches: [ develop ]

jobs:
  build:
    name: PR Checker
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Gradle cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: 17

      - name: Setup Android SDK
        uses: android-actions/setup-android@v2

      - name: Change gradlew permissions
        run: chmod +x ./gradlew

      - name: Touch local properties
        run: touch local.properties

      - name: Access CAKK_BASE_URL
        env:
            CAKK_BASE_URL: ${{ secrets.CAKK_BASE_URL }}
        run: echo "CAKK_BASE_URL=\"CAKK_BASE_URL\"" >> local.properties

      - name: Access NAVER_API_MAP_KEY
        env:
            NAVER_API_MAP_KEY: ${{ secrets.NAVER_API_MAP_KEY }}
        run: echo "NAVER_API_MAP_KEY=\"$NAVER_API_MAP_KEY\"" >> local.properties

      - name: Access FILTER_PREFERENCES
        env:
          FILTER_PREFERENCES: ${{ secrets.FILTER_PREFERENCES }}
        run: echo "FILTER_PREFERENCES=\"FILTER_PREFERENCES\"" >> local.properties

      - name: Lint Check
        run: ./gradlew ktlintCheck

      - name: Run unit tests
        run: ./gradlew testDebugUnitTest

      - name: Build debug APK
        run: ./gradlew assembleDebug --stacktrace

      - name: Create android test report
        uses: asadmansr/android-test-report-action@v1.2.0
        if: ${{ always() }}
